import { tv, type VariantProps } from 'tailwind-variants';

export type CommandVariants = VariantProps<typeof commandTheme>;

export const commandTheme = tv(
  {
    slots: {
      command: [
        'bg-surface-base',
        'text-text-em-high',
        'flex',
        'h-full',
        'w-full',
        'flex-col',
        'overflow-hidden',
        'rounded-lg',
        'border',
        'border-border-base',
      ],
      commandDialogContent: ['overflow-hidden', 'py-0', 'sm:py-0'],
      commandInputWrapper: ['flex', 'items-center', 'px-5', 'gap-3'],
      commandInputIcon: ['text-[18px]', 'shrink-0', 'text-text-em-low'],
      commandInput: [
        'h-14',
        'flex',
        'placeholder:text-text-em-placeholder',
        'w-full',
        'bg-transparent',
        'py-2',
        'outline-none',
        'disabled:cursor-not-allowed',
        'disabled:opacity-50',
      ],
      commandList: ['max-h-[300px]', 'overflow-y-auto', 'overflow-x-hidden'],
      commandEmpty: ['py-3', 'px-5', 'text-left'],
      commandGroup: [
        'text-text-em-mid',
        'bg-surface-base',
        'overflow-auto',
        'p-2',
        '[&_[cmdk-group-heading]]:text-text-em-low',
        '[&_[cmdk-group-heading]]:px-2',
        '[&_[cmdk-group-heading]]:py-1.5',
        '[&_[cmdk-group-heading]]:text-xs',
        '[&_[cmdk-group-heading]]:font-medium',
      ],
      commandSeparator: ['bg-border-base', '-mx-4', 'h-px'],
      commandItem: [
        'transition-default',
        'text-text-em-high',
        'relative',
        'flex',
        'items-center',
        'justify-between',
        'select-none',
        'rounded-lg',
        'px-4',
        'py-3',
        'outline-none',
        'focus-ring',
        'hover:bg-element-tertiary',
        'data-[active]:bg-element-tertiary/80',
        'overflow-hidden',
        'data-[selected=true]:bg-element-tertiary',
        'data-[selected=true]:data-[active]:bg-element-tertiary',
        'data-[disabled=true]:cursor-not-allowed',
        'data-[disabled=true]:text-text-em-low',
      ],
      commandShortcut: [
        'ml-auto',
        'text-xs',
        'tracking-widest',
        'text-text-em-low',
      ],
    },
    variants: {
      variant: {
        combobox: {
          command: ['max-h-60', 'border-none'],
          commandItem: [
            'px-2',
            'py-1.5',
            'first:mt-2',
            'last:mb-2',
            '[&:not(:first-child)]:mt-1',
          ],
          commandList: ['-mx-2'],
          commandInput: ['px-0', 'h-11'],
          commandInputWrapper: ['px-0'],
          commandEmpty: ['px-0'],
        },
        dialog: {
          command: [],
          commandItem: [],
          commandInput: [],
        },
      },
    },
  },
  { responsiveVariants: true },
);
